- packages/rax-link/package.json
- packages/rax-link/src/miniapp-wechat/index.wxml
> fix rax-link bindtap

- packages/rax-recyclerview/README.md
- packages/rax-recyclerview/package.json
- packages/rax-recyclerview/src/miniapp-wechat/fmtEvent.ts
- packages/rax-recyclerview/src/miniapp-wechat/index.json
- packages/rax-recyclerview/src/miniapp-wechat/index.ts
- packages/rax-recyclerview/src/miniapp-wechat/index.wxml
- packages/rax-recyclerview/src/miniapp/index.ts
1. Feat: support wechat miniprogram recyclerview
2. Docs: refactor  README
> feat: support wechat miniprogram recyclerview

- packages/rax-slider/package.json
> chore: bump version

- packages/rax-picture/package.json
- packages/rax-picture/src/optimizer/index.ts
- packages/rax-picture/src/optimizer/scaling.ts
- packages/rax-picture/src/webp.ts
- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/timer.ts
Make rax-picture and rax-scrollview work in SSR
> Feat: Support SSR

- packages/rax-slider/package.json
- packages/rax-slider/src/miniapp-wechat/index.ts
- packages/rax-slider/src/miniapp/index.ts
In miniapp, method should in methods property.
> fix: slider slideTo method

- packages/rax-icon/package.json
> feat: v1.1.2

- packages/rax-picture/src/webp.ts
> fix: ios without webp

- packages/rax-image/package.json
PR [https://github.com/raxjs/rax-components/pull/84](https://github.com/raxjs/rax-components/pull/84) need publish
> Fix image update

- packages/rax-modal/package.json
- packages/rax-modal/src/index.css
- packages/rax-modal/src/index.tsx
- packages/rax-modal/src/miniapp-wechat/index.js
- packages/rax-modal/src/miniapp-wechat/index.wxml
- packages/rax-modal/src/miniapp/index.axml
- packages/rax-modal/src/miniapp/index.js
- 解决滚动穿透问题，并修复 #88 
- 解决 onHide 触发两次的问题
- 支付宝小程序兼容 component1 模式
> refactor: modal

- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/index.css
- packages/rax-scrollview/src/index.tsx
previous default style with flex 1 cause not working with style height, now fix the style problem with the alternative style flex
1. without flex style when style with height prop
2. with default flex style when style without height prop
> fix: scrollview style flex

- packages/rax-textinput/package.json
> fix: dependency

- packages/rax-slider/package.json
- packages/rax-slider/src/slider.weex.tsx
Fix slideTo methid in Weex:
[https://github.com/alibaba/rax/issues/1668](https://github.com/alibaba/rax/issues/1668)
> Fix Slider's  'slideTo' method in Weex

- packages/rax-xslider/README.md
- packages/rax-xslider/demo/index.js
- packages/rax-xslider/package.json
- packages/rax-xslider/src/mods/Util.js
- packages/rax-xslider/src/mods/views/BaseView.js
- packages/rax-xslider/src/mods/views/DefaultView.js
fix the bug of xslider, replace 'rpx' with 'rem'
remove 'forceTransition: true'
> Fix rax-xslider unit bug

- packages/rax-video/package.json
https://github.com/raxjs/rax-components/commit/f2387bffdf81cb99ad3b709c19f055dcb804e636
上一个提交并没有发布新的版本，现在需要重新发一下
> feat: upgrade rax-video versions

- packages/rax-link/README.md
- packages/rax-link/package.json
- packages/rax-link/src/quickapp/index.ux
> Feat quickapp link

- packages/rax-xslider/package.json
fix h5 {loop: true} bug by updating the version of style-unit
> Fix xslider h5 loop bug

- packages/rax-xslider/package.json
- packages/rax-xslider/src/mods/Util.js
- packages/rax-xslider/src/mods/views/BaseView.js
no rem unit, so we remove the unit format,
after appearing, excute playing immediately
> Fix xslider transform value format

- packages/rax-canvas/package.json
- packages/rax-canvas/src/index.js
修复 props 中 width 和 height 未传值时，customStyle.width customStyle.height 设置失效问题
修复传递 rpx 单位时，canvas width height 属性无效问题
> fix: with & height props error

- packages/rax-scrollview/demo/index.jsx
- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/web/index.tsx
> fix(scroll-view): scrollIntoView rolling distance

- packages/rax-view/package.json
- packages/rax-view/tsconfig.json
> fix: rax-view tsconfig

- package.json
- packages/rax-icon/package.json
- packages/rax-icon/src/index.tsx
issue: https://github.com/raxjs/rax-components/issues/186
> Fix rax icon dom module require

- packages/rax-recyclerview/package.json
> Fix rax-recyclerview error

- packages/rax-slider/package.json
Fix  rax-slider dev server preview error.  cause by rax-image and universal-env
> Fix rax-slider dev server error

- packages/rax-modal/README.md
- packages/rax-modal/package.json
- packages/rax-modal/src/index.tsx
- packages/rax-modal/src/miniapp-wechat/index.js
- packages/rax-modal/src/miniapp/index.js
- packages/rax-modal/src/quickapp/index.ux
- packages/rax-modal/src/types.ts
- 修复直接移除 modal dom 时，body 依然处于锁定滚动状态的问题
- 修复多次点击 mask，onHide 被重复触发的问题
> fix: modal action

- packages/rax-slider/package.json
- packages/rax-slider/src/bytedance-microapp/index.ts
- packages/rax-slider/src/miniapp/index.ts
- packages/rax-slider/src/wechat-miniprogram/index.ts
Fix: 小程序上轮播，循环时从尾页到第一页应该和文档描述一致，为循环切换
> fix: slider loop

- packages/rax-image/package.json
- packages/rax-image/src/__tests__/Image.js
- packages/rax-image/src/index.tsx
> Release: rax-image v2.2.1

- packages/rax-scrollview/index.d.ts
- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/miniapp-native/bytedance-microapp/index.ts
- packages/rax-scrollview/src/miniapp-native/bytedance-microapp/index.wxml
- packages/rax-scrollview/src/miniapp-native/miniapp/index.axml
- packages/rax-scrollview/src/miniapp-native/miniapp/index.ts
- packages/rax-scrollview/src/miniapp-native/wechat-miniprogram/index.ts
- packages/rax-scrollview/src/miniapp-native/wechat-miniprogram/index.wxml
- packages/rax-scrollview/src/throttle.ts
- packages/rax-scrollview/src/timer.ts
- packages/rax-scrollview/tsconfig.json
1. 支持 id 属性透传
2. 修复 types 相关编译问题
> feat(rax-scrollview): add id for miniapp

- packages/rax-video/package.json
- packages/rax-video/src/index.tsx
- remove autoPlay attribute if set autoPlay to false in web
- support autoPlay in miniapp runtime
> fix(rax-video): autoPlay attribute support in web and miniapp runtime

- packages/rax-refreshcontrol/README.md
- packages/rax-refreshcontrol/package.json
- packages/rax-refreshcontrol/src/types.ts
之前代码的 props 少了 pullingdown，且类型定义是错的，把 pullingdown 事件的类型放到了 refresh 事件上了
> Fix refreshcontrol event

- packages/rax-textinput/package.json
- packages/rax-textinput/src/__tests__/TextInput.js
- packages/rax-textinput/src/__tests__/TextInput.weex.js
- packages/rax-textinput/src/index.tsx
避免在 SSR 场景下将 comment 渲染到 textarea 中
> fix: should not render comment as value in ssr

- packages/rax-slider/package.json
- packages/rax-slider/src/slider.web.tsx
> fix: reset timer each call slideTo.

- .gitignore
- packages/rax-text/package.json
- packages/rax-text/src/index.tsx
- packages/rax-view/package.json
- packages/rax-view/src/index.tsx
- rax-view 使用小程序原生 view 渲染，支持 onAppear onDisappear onFirstAppear
- rax-text 使用小程序原生 text 渲染，支持 number-of-lines
> feat: support view text more base property

- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/miniapp-native/wechat-miniprogram/index.wxml
rax-scrollView add enableFlex attribute
fix wechat-miniapp  don't have flex attribute
> feat:scrollView add enableFlex attr

- packages/rax-text/CHANGELOG.md
- packages/rax-text/package.json
- packages/rax-view/CHANGELOG.md
- packages/rax-view/package.json
Feat add rax-view and rax-text changelog
> Feat add rax-view and rax-text changelog

- packages/rax-scrollview/CHANGELOG.md
- packages/rax-scrollview/package.json
> Feat update rax-scrollview

- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/index.css
- packages/rax-scrollview/src/index.tsx
Feat update scrollview css specificity
> Feat update scrollview css specificity

- packages/rax-slider/package.json
- packages/rax-slider/src/slider.web.tsx
Use transformX to reduce relayout.
> Fix performance issue.

- packages/rax-xslider/package.json
- packages/rax-xslider/src/mods/Util.js
- packages/rax-xslider/src/mods/views/BaseView.js
- packages/rax-xslider/src/mods/views/DefaultView.js
- packages/rax-xslider/src/mods/views/ListView.js
使用 `instanceof Array` 来判断是否数组，在天马环境下，可能因为不同的上下文，导致判断失败
> fix: array in multiple context

- packages/rax-text/CHANGELOG.md
- packages/rax-text/package.json
- packages/rax-view/CHANGELOG.md
- packages/rax-view/package.json
Feat update text and view in weex
> Feat update text and view in weex

- packages/rax-swiper/package.json
修复 rax-swiper 内网入库问题，同步内外 rax-swiper 版本，验证一键入库逻辑
> chore: update rax-swiper version

- packages/rax-scrollview/CHANGELOG.md
- packages/rax-scrollview/package.json
> Feat sync pegasus

- CHANGELOG.md
- packages/rax-portal/demo/index.jsx
- packages/rax-portal/package.json
- packages/rax-portal/src/index.tsx
目前版本，container变化后不会触发重渲染，导致组件不响应container变化
> fix(Portal): not re-render when the container changes

- packages/rax-textinput/src/types.ts
> fix(TextInput): add types

- packages/rax-scrollview/CHANGELOG.md
- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/web/index.tsx
fix: scrollView animated "scrollLeft" of null problem.
> fix: scrollView animated

- packages/rax-slider/CHANGELOG.md
- packages/rax-slider/package.json
> Sync from rax-pkg-rax-slider

- packages/rax-slider/CHANGELOG.md
- packages/rax-slider/package.json
- packages/rax-slider/src/index.tsx
[fix] Project in MiniApp WebView with `appx/web-view.min.js` render error.
> Fix Project in MiniApp WebView render error.

- packages/rax-modal/CHANGELOG.md
- packages/rax-modal/package.json
- packages/rax-modal/src/index.css
- packages/rax-modal/src/index.tsx
修复：在安卓浏览器中，当 modal 为 visible 时，滑动窗口 body 依然会滑动的问题
> fix overflow in android web

- packages/rax-slider/CHANGELOG.md
- packages/rax-slider/package.json
- packages/rax-slider/src/types.ts
> feat: update slider types

- packages/rax-slider/src/web/index.tsx
> fix slider build error

- packages/rax-swiper/CHANGELOG.md
- packages/rax-swiper/README.md
- packages/rax-swiper/package.json
- packages/rax-swiper/src/miniapp-native/ali-miniapp/index.ts
- packages/rax-swiper/src/miniapp-native/bytedance-microapp/index.ts
- packages/rax-swiper/src/miniapp-native/wechat-miniprogram/index.ts
- packages/rax-swiper/src/miniapp-runtime/swiper.tsx
- packages/rax-swiper/src/web/swiper.js
> feat: return instance && make same

- packages/rax-view/CHANGELOG.md
- packages/rax-view/package.json
- packages/rax-view/src/common/index.tsx
- packages/rax-view/src/index.tsx
- packages/rax-view/src/weex/index.tsx
Directly use dom styles in weex v2
> feat: rax-view support weex v2

- packages/rax-waterfall/CHANGELOG.md
- packages/rax-waterfall/package.json
- packages/rax-waterfall/src/common/index.js
- packages/rax-waterfall/src/utils/omit.js
> feat(waterfall): update rax-scrollview version

- packages/rax-scrollview/CHANGELOG.md
- packages/rax-scrollview/package.json
- packages/rax-scrollview/src/web/index.tsx
修复此问题 https://github.com/raxjs/rax-components/issues/431
> fix(rax-scrollview): 修复没有scrollerNode时页面白屏

- packages/rax-swiper/CHANGELOG.md
- packages/rax-swiper/package.json
- packages/rax-swiper/src/web/init-swiper.js
> fix: fix css of swiper build error

- packages/rax-video/CHANGELOG.md
- packages/rax-video/package.json
- packages/rax-video/src/web/index.tsx
Give a default value otherwise will emit an error when no error handler be passed.
> fix(rax-video): set default value for onPlayError

- package.json
- packages/rax-swiper/CHANGELOG.md
- packages/rax-swiper/package.json
> fix: update version for rax-swiper
