raxjs/rax-components

.github/workflows/auto-publisher.yml
package.json
packages/rax-empty/package.json
scripts/check-and-publish.js

- 组件和 API 包发布权限收敛到发布机器人，杜绝人为干预发布过程，产生各种操作失误。
- 所有发布需要走 PR 和 Review 流程并合并到 Master 分支后自动触发，避免私下发布的问题。
- 脚本会对比本地版本与线上版本差异，并根据版本规则自动识别 beta/latest tag，然后构建发布到 npm。

chore: check and publish automaticlly

---

packages/rax-text/package.json
packages/rax-text/src/miniapp-wechat/index.ts
packages/rax-text/src/miniapp-wechat/index.wxml
packages/rax-text/src/miniapp-wechat/index.wxss

1. 微信小程序的 text 组件里用 slot 会有渲染不及时的 bug
2. 修复微信小程序的多行属性其实根本没生效的问题

fix: wechat miniprogram text render

---

packages/rax-image/src/index.tsx

fix https://github.com/raxjs/rax-components/issues/83
顺便修复了 useCallback 的错误用法，以及不提供 source 或 uri 直接不渲染 image 组件的问题

fix: 修复 rax-image source 改变不会更新图片的问题

---

packages/rax-picture/package.json
packages/rax-picture/src/optimizer/scaling.ts

当图片宽度为 px 单位时，当前计算规则无法根据真实图片尺寸进行缩放，因为只计算了 rpx 的情况。
当图片单位为 rem vw 等单位时，在无法匹配适合最小宽度的情况下会走默认值与当前逻辑一致

feat: use px in scaling

---

packages/rax-countdown/package.json
packages/rax-countdown/src/index.js

去除模板为 `{d}-{h}-{m}-{s}` 形式带来的空节点

fix: empty node in countdown

---

packages/rax-modal/package.json
packages/rax-modal/src/types.ts

* 测试代码：
```jsx
<Modal>
<div>foooooo</div>
</Modal>
```
* 在 ts 环境下 children 类型报错
Modal 的 children 之前定义为 ComponentType[]，有两个问题，一个是 Modal 的 children 为 element 类型而不是 component，第二个是 children 不一定是数组，参考 typescript 官网对于 [ React children type](https://www.typescriptlang.org/docs/handbook/jsx.html#children-type-checking) 的定义，将 Rax 中 children 定义为 RaxElement 类型

fix: rax-modal types

---

packages/rax-picture/package.json
packages/rax-picture/src/optimizer/scaling.ts

在图片后缀尺寸拼接的判断逻辑中，原有 return false 的方式会中断后缀的对比逻辑，导致图片尺寸异常。

Fix rax picture scaling

---

packages/rax-slider/package.json
packages/rax-slider/src/slider.web.tsx

rax-slider shouldn't autoPlay and swiped when children length is less than 2.

Fix slider auto play when children length is 1

---

packages/rax-canvas/README.md
packages/rax-canvas/package.json
packages/rax-canvas/src/wechat-miniprogram/index.js
packages/rax-canvas/src/wechat-miniprogram/index.wxml

微信小程序使用 `wx.createCanvasContext` 时，组件 `type` 必须为空，否则画布不会绘制

fix: wechat canvas type

---

packages/rax-text/package.json
packages/rax-text/src/miniapp/index.acss
packages/rax-text/src/miniapp/index.axml

rax-text@1.2.0 及以前的版本中，小程序的实现样式为 inline，表现和 Web 不一致，在 1.3.0 的版本中对齐了表现，但是导致 1.2.0 及以前的版本的业务出现 break 的兼容问题。故目前需要回退到 1.2.0 以前的代码，并在 2.0 之后的版本对齐其它端的表现。

chore: remove miniapp text default style

---

package.json
packages/rax-countdown/package.json
packages/rax-countdown/src/index.js
packages/rax-countdown/src/miniapp/index.axml
packages/rax-countdown/src/miniapp/index.ts

1. Days larger than 99  is not displayed correctly in miniapp
correct：
error：
2. add key for items to avoid warning

fix: time duration in miniapp

---

packages/rax-textinput/src/miniapp-wechat/index.ts
packages/rax-textinput/src/miniapp/index.ts

* issue: https://work.aone.alibaba-inc.com/issue/26039370 
* 原因：当前 rax-textInput 组件支付宝小程序默认 keyboardType 设置的是 default，为不支持的值，支付宝小程序会将其解析成 number 类型，默认值与 web 和微信小程序不一致（text 类型），导致多端投放时当未设置 keyboardType 时行为不一致
* fix: 
抹平 web 与支付宝、微信 miniapp 三端 keyboardType 默认值差异
1. 支付宝 miniapp 默认值改为 text
2. 支付宝、微信 miniapp 端设置不支持的 keyboardType 时转成默认值

fix: default keyboardType behave different across web and miniapp

---

packages/rax-scrollview/demo/index.jsx
packages/rax-scrollview/package.json
packages/rax-scrollview/src/index.css
packages/rax-scrollview/src/web/index.tsx

This is demo from rax-scrollview, can't scroll and jump to target child element.
Fix this bug:

Fix rax-scrollview container height

---

packages/rax-image/src/index.tsx

web上e.success为undefined，undefined !== null 为真，会进入weex的判断逻辑

fix(rax-image): 修复web上rax-image的onLoad事件无法调到的问题

---

packages/rax-modal/demo/index.jsx
packages/rax-modal/package.json
packages/rax-modal/setup.js
packages/rax-modal/src/__tests__/modal.test.js
packages/rax-modal/src/index.tsx
packages/rax-modal/src/types.ts

1. 修复 modal 应该在 show 之后，将 opacity 终态设置为 1 的逻辑
2. 添加定时器兜底逻辑，当动画在动画过渡时间内没有执行回调时，即 universal-transition 失效时，强制执行回调

fix(rax-modal): modal opacity

---

packages/rax-icon/package.json
packages/rax-icon/src/index.tsx
packages/rax-icon/src/miniapp/index.ts

钉钉小程序中没有 `my.loadFontFace` 的实现，因此，添加兼容以及 warning 提示

chore: compatible dingding

---

packages/rax-gesture-view/package.json
packages/rax-gesture-view/src/gesture.web.tsx
packages/rax-gesture-view/src/types.ts

1. 去掉 HorizontalPan 上关于垂直判断的逻辑 Math.abs(this.maxDy) < threshold
去掉 VerticalPan 上关于水平判断的逻辑 Math.abs(this.maxDx) < threshold
原因：
1. 已经有水平/垂直方向的 threshold 以及两个方向的 touchActionRatio 这两个条件判断
2. 在客户端的横滑容器内，如果前端组件不处理事件时就会被客户端内拦截，导致后续前端事件无法接收，例如在 HorizontalPan 内，如果加了垂直方向的判断，就会比较容易被端上拦截，导致后续横滑失效
2. 增加 threshold 的 props 透传

fix: gesture-view horizontal/vertical pan threadhold

---

packages/rax-slider/package.json
packages/rax-slider/src/SwipeEvent.tsx

Fixed:
`Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

Fix cancelable false error

---

packages/rax-slider/package.json
packages/rax-slider/src/slider.miniapp.tsx

支付宝小程序中 swiper 接受事件为 onChange 而非 onSwiperChange

fix(slider): onSwiperChange should be replaced by onChange

---

packages/rax-text/package.json
packages/rax-text/src/index.tsx

According React's implement, vendor prefixes should begin with a capital letter.
In Rax Server Renderer followed this rule, so `webkitLineClamp` can not be render correctly.
But in driver-universal 1.x, `WebkitLineClamp` will be filtered，so this is a break change for apps still use driver-universal 1.x.
https://reactjs.org/docs/dom-elements.html#style
需要 breakchange 是因为，driver-universal 1.x 版本中对 `WebkitLineClamp` 的处理有问题，会为其转换上单位，因此改动后，rax-text 只能在新版本 driver 使用

fix: capitalize verdor prefix for SSR

---

packages/rax-recyclerview/package.json
packages/rax-recyclerview/src/miniapp-wechat/index.ts

recyclerview onScroll triggers the onEndReached event incorrectly in wechat miniapp

fix(rax-recyclerview): onScroll triggers incorrect event in wechat

---

packages/rax-textinput/package.json
packages/rax-textinput/src/index.tsx

`readonly` and `disabled` standardizing

fix: input editable

---

packages/rax-canvas/package.json

1. rax-canvas should build es dir
2. Use `es/index.js` instead of `src/index.js` as rax-canvas `module` field's value

fix: rax-canvas module field

---

packages/rax-video/package.json
packages/rax-video/src/index.tsx

fix(video): props transform in runtime miniapp

---

CHANGELOG.md
packages/rax-textinput/package.json
packages/rax-textinput/src/index.tsx

支付宝所支持的类型有限，但实际上传入不支持的类型会导致其他情况出现。
例如支付宝原生并不支持type=search。使用Rax编写多端应用时，传入了keyboardType=web-search，在Web上表现正常，但在支付宝小程序中会导致iOS只能唤起数字键盘。
修复方式是进行二次检查。支付宝默认支持text、 number、 idcard、 digit 四种类型。其他类型（包括 numberpad、digitpad、 idcardpad）和后续继续增加更多的类型，可以通过canIUse进行判断。如果不支持，则fallback到text

fix(TextInput): check input types

---

packages/rax-slider/CHANGELOG.md
packages/rax-slider/demo/index.jsx
packages/rax-slider/package.json
packages/rax-slider/src/slider.web.tsx

- [fix] Method `slideTo` not as expected problem.
- [fix] Props `index` not work in first rendering.
- [feat] Update slide animation.
- [feat] Update component`rax-view`.
对齐文档说明 https://rax.js.org/docs/components/slider

fix: slideTo and index

---

packages/rax-canvas/package.json
packages/rax-embed/package.json
packages/rax-icon/package.json
packages/rax-image/package.json
packages/rax-link/package.json
packages/rax-qrcode/package.json
packages/rax-scrollview/package.json
packages/rax-slider/package.json
packages/rax-text/package.json
packages/rax-textinput/package.json
packages/rax-video/package.json

feat(jsx2mp): add miniprogram config to support used in wechat

---

packages/rax-slider/CHANGELOG.md
packages/rax-slider/package.json
packages/rax-slider/src/slider.miniapp.tsx
packages/rax-slider/src/slider.weex.tsx

prop `onChange` is missing in deps of Slider's `handleChange` function, which causes rax-slider to call the old version of `onChange`.

fix: missing deps on onChange

---

packages/rax-barcode/demo/index.md
packages/rax-canvas/demo/index.md
packages/rax-countdown/demo/index.md
packages/rax-gesture-view/demo/index.md
packages/rax-icon/demo/index.md
packages/rax-image/demo/index.md
packages/rax-link/demo/index.md
packages/rax-modal/demo/index.md
packages/rax-parallax/demo/index.md
packages/rax-portal/demo/index.md
packages/rax-qrcode/demo/index.md
packages/rax-recyclerview/demo/index.md
packages/rax-scrollview/demo/index.md
packages/rax-slider/demo/index.md
packages/rax-textinput/demo/index.md
packages/rax-video/demo/index.md
packages/rax-view/demo/index.md
packages/rax-waterfall/demo/index.md

修复外层 build-scripts 升级大版本（仅支持预览 md 文件） 导致 demo/xxx.jsx 无法预览问题。
1. 仅修改 demo/index.jsx 保证组件可预览；
2. build-scripts 层需支持预览 jsx 文件。

修复组件预览失败问题

---

packages/rax-modal/CHANGELOG.md
packages/rax-modal/package.json

rax-modal 依赖的 rax-text 和 rax-view 升级到 2.x
https://github.com/raxjs/rax-components/issues/365

fix: up deps of rax-modal

---

packages/rax-scrollview/CHANGELOG.md
packages/rax-scrollview/package.json
packages/rax-scrollview/src/web/index.tsx

如果onEndReachedThreshold值为number的时候，endReachedThreshold为NaN，最终导致onEndReached不会触发的问题

fix: pixelRatio没有初始化导致endReachedThreshold为NaN

---

packages/rax-swiper/CHANGELOG.md
packages/rax-swiper/package.json
packages/rax-swiper/src/web/swiper.css

- fix(rax-swiper): calc error in css file caused by `postcss-calc`(issue: https://github.com/postcss/postcss-calc/issues/119)
- chore: bump version

fix(rax-swiper): calc error in css file caused by `postcss-calc`

---

packages/rax-swiper/CHANGELOG.md
packages/rax-swiper/package.json
packages/rax-swiper/src/miniapp-runtime/swiper.tsx

在运行时小程序中，swiper 的 onChange 回调 是通过 `change` 事件触发的。
本 pr 修复了在 swiper 内其他节点触发 `change` 事件时影响 activeIndex 的情况。

fix(rax-swiper): stop bubble in runtime miniapp

---

packages/rax-recyclerview/CHANGELOG.md
packages/rax-recyclerview/README.md
packages/rax-recyclerview/package.json
packages/rax-recyclerview/src/index.js
packages/rax-scrollview/CHANGELOG.md
packages/rax-scrollview/package.json
packages/rax-scrollview/src/weex/index.tsx

- fix scrollTo and scrollIntoView method in scroller for Weex 2.0
- add scrollTo and scrollIntoView method in recyclerview for Weex 2.0
- add scrollIntoView in recyclerview for Web when needRecycler is false

feat: Weex 2.0 support scrollTo and scrollIntoView in scrollview and recyclerview

---

packages/rax-swiper/package.json
packages/rax-textinput/CHANGELOG.md
packages/rax-textinput/package.json
packages/rax-textinput/src/index.tsx
packages/rax-textinput/src/miniapp-native/ali-miniapp/index.axml
packages/rax-textinput/src/miniapp/index.axml

maxlength 是一个不合法的 dom 属性，在 react runtime 中会抛出 warning。
random-number 是一个小程度中随机数键盘的属性，在 web  中 N 大写不符合 custom property 的标准，否则会抛出 warning。
close #456

fix: maxlength is invalid property in dom

---

packages/rax-textinput/CHANGELOG.md
packages/rax-textinput/package.json
packages/rax-textinput/src/index.tsx

close #459 
这次的版本修改是这个 https://github.com/raxjs/rax-components/pull/457 ，为了兼容 React 运行时白名单校验 props 的问题，里面把 maxlength 改成了 maxLength，否则在 React runtime 中会抛出错误。
原因是，maxlength 在 web 标准或者说在 input 的props 中不存在，所以走的是兜底 attributes 的逻辑，而 maxLength 走的是 input element 的 props 的逻辑。按照标准，应该走 maxLength 更合适，包括 React 中也会有白名单校验。但是业务中用法是当 schema 中不存在 maxlength 时，会设置一个空字符串""到 maxlength 中。原本组件 maxlength 设置空字符串，走了 attributes 逻辑没有问题，设置无效，但是当走了 props 时，在 web 引擎中会做校验，把 '' 变成 0，所以导致了无法输入。
讨论： 未来需要把 rax 体系支持在 React 上运行的同事，为了保证成本以及降低目前已使用 Rax 体系用户的影响，后续考虑把这些 compat 逻辑统一放到 rax-compat 中，以兼容 Rax 体系在 React runtime 上的正确运行。

revert: revert maxlength for compat set maxlength to empty string.

---

packages/rax-scrollview/CHANGELOG.md
packages/rax-scrollview/package.json
packages/rax-scrollview/src/web/index.tsx

当 disbaleScroll 初始值为 false 时，再次设置为 true，不会生效，ScrollView 依然不能滚动。原因是 overflow 属性虽然被 delete 了，但没有被重新赋值。

fix: disable scroll not working

---

packages/rax-scrollview/CHANGELOG.md
packages/rax-scrollview/package.json
packages/rax-scrollview/src/types.ts

ScrollViewRefObject 中没有 scrollIntoView，在useRef中传入泛型调用会提示没有对应api

feat: add scrollIntoView attribute in ScrollViewRefObject interface

---

packages/rax-swiper/CHANGELOG.md
packages/rax-swiper/package.json
packages/rax-swiper/src/web/init-swiper.js

swiper >= 8.4.4 版本同时支持了 webpack 4 的路径 resolve 和 webpack 5 的 exports 字段 resolve, 所以跟进这个版本, 更新一个版本

feat: support webpack 4 and 5
